// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt68RiIrnadsHAvDKC5qCF62Bo-hiJhEw',
    appId: '1:348903015241:web:c68bc25f60eb9c4f00d098',
    messagingSenderId: '348903015241',
    projectId: 'narcissus-364913',
    authDomain: 'narcissus-364913.firebaseapp.com',
    storageBucket: 'narcissus-364913.appspot.com',
    measurementId: 'G-DKC1YNPR32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtNq0vfVCjzjTE-pTgPpdR0ntgEg4KVCE',
    appId: '1:348903015241:android:88926e80af428a8300d098',
    messagingSenderId: '348903015241',
    projectId: 'narcissus-364913',
    storageBucket: 'narcissus-364913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmOBw2cKyfobBG_kBUkobIhf1BKRlecdA',
    appId: '1:348903015241:ios:01f2c10ef07b8dc100d098',
    messagingSenderId: '348903015241',
    projectId: 'narcissus-364913',
    storageBucket: 'narcissus-364913.appspot.com',
    iosClientId: '348903015241-udr062hkea65h022scebbbqogtu2o003.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
